# Performing Naive Bayes Algorithm on Titanic Dataset

In [145]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.naive_bayes import BernoulliNB

In [146]:
df = pd.read_csv('./Day 24 Assignment/train.csv')

df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [147]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  889 non-null    int64  
 1   Survived     889 non-null    int64  
 2   Pclass       889 non-null    int64  
 3   Name         889 non-null    object 
 4   Sex          889 non-null    object 
 5   Age          889 non-null    float64
 6   SibSp        889 non-null    int64  
 7   Parch        889 non-null    int64  
 8   Ticket       889 non-null    object 
 9   Fare         889 non-null    float64
 10  Cabin        202 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.5+ KB


In [148]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [149]:
df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin', 'Age', 'Fare'], axis=1, inplace=True)

df.head()

Survived  Pclass     Sex  SibSp  Parch Embarked
0         0       3    male      1      0        S
1         1       1  female      1      0        C
2         1       3  female      0      0        S
3         1       1  female      1      0        S
4         0       3    male      0      0        S

In [150]:
df.columns

Index(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked'], dtype='object')

In [151]:
# Using LabelEncoder on 'Sex' variable

le = LabelEncoder()

df['Sex'] = le.fit_transform(df['Survived'])
df['Sex'].unique()

array([0, 1], dtype=int64)

In [152]:
df['Embarked'] = le.fit_transform(df['Embarked'])
df['Embarked'].unique()

array([2, 0, 1])

In [153]:
df.head()

Survived  Pclass  Sex  SibSp  Parch  Embarked
0         0       3    0      1      0         2
1         1       1    1      1      0         0
2         1       3    1      0      0         2
3         1       1    1      1      0         2
4         0       3    0      0      0         2

In [154]:
from sklearn.model_selection import train_test_split

In [158]:
def new_var(features):
    
    for i in features:
        X = df.drop(i, axis=1)
        y = df[i]
                  
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
        model = BernoulliNB()
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        acc = accuracy_score(y_test, y_pred, normalize=True)
        cm = confusion_matrix(y_test, y_pred)
        print('The accuracy score with Dependent variable as', i, 'and others being Independent variable, is :', acc, '\n')
        print('The confusion matrix :\n', cm, '\n\n\n')
    

features = df[['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked']]
new_var(features)

The accuracy score with Dependent variable as Survived and others being Independent variable, is : 1.0 

The confusion matrix :
 [[157   0]
 [  0 110]] 



The accuracy score with Dependent variable as Pclass and others being Independent variable, is : 0.5917602996254682 

The confusion matrix :
 [[ 36  10  24]
 [ 12  13  24]
 [ 36   3 109]] 



The accuracy score with Dependent variable as Sex and others being Independent variable, is : 1.0 

The confusion matrix :
 [[157   0]
 [  0 110]] 



The accuracy score with Dependent variable as SibSp and others being Independent variable, is : 0.6891385767790262 

The confusion matrix :
 [[165  17   0   0   0   0   0]
 [ 46  19   0   0   0   0   0]
 [  6   2   0   0   0   0   0]
 [  7   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0]] 



The accuracy score with Dependent variable as Parch and others being Independent variable, is : 0.7228464419475655 

The confusion matrix 