# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np

In [5]:
np.random.rand(3,3,3)

array([[[0.47986207, 0.42928975, 0.00726203],
        [0.06562293, 0.10087019, 0.87611389],
        [0.20503235, 0.5881523 , 0.65414777]],

       [[0.16740884, 0.21608515, 0.326289  ],
        [0.56784539, 0.95690039, 0.42389102],
        [0.69972553, 0.61370324, 0.72464864]],

       [[0.53383527, 0.22538213, 0.95889598],
        [0.92915094, 0.12586889, 0.42718443],
        [0.44548057, 0.19972997, 0.26654687]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [38]:
print(np.diag(1+np.arange(5), k=-1))

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [10]:
arr2 = np.zeros((8,8))

# Creating a checkerboard pattern with zeros & ones
arr2[1::2 , ::2] = 1
arr2[::2 , 1::2] = 1
print(arr2)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [36]:
arr = np.random.random((3,3))
print("The Original matrix : \n", arr)

normalize = (arr - np.mean(arr)) / (np.std(arr))
print('\n The normalized matrix : \n', normalize)

The Original matrix : 
 [[0.35952609 0.09660463 0.13241562]
 [0.51323011 0.1470598  0.24223254]
 [0.90424461 0.60206763 0.85789749]]

 The normalized matrix : 
 [[-0.23618994 -1.13829682 -1.01542615]
 [ 0.2911822  -0.96518065 -0.63863454]
 [ 1.63278767  0.59599163  1.47376659]]


# 5.  How to find common values between two arrays?

In [12]:
ar1 = np.array([5,10,15,20,25])
ar2 = np.array([15,16,17,18,19,20])
print("First array :", ar1)
print("Second array :", ar2)
print('\n')
print("Common values from the 2 arrays are :", np.intersect1d(ar1,ar2))

First array : [ 5 10 15 20 25]
Second array : [15 16 17 18 19 20]


Common values from the 2 arrays are : [15 20]


# 6.How to get the dates of yesterday, today and tomorrow?

In [13]:
print("Today is :", np.datetime64('today'))
print("Yesterday was :", np.datetime64('today') - 1)
print("Tomorrow is :", np.datetime64('today') + 1)

Today is : 2020-07-29
Yesterday was : 2020-07-28
Tomorrow is : 2020-07-30


# 7. Consider two random array A and B, check if they are equal

In [20]:
arr_A = np.array([12,24,36,48])
arr_B = np.array([12,24,46,48])
z = np.equal(arr_A,arr_B)
print(z)

[ True  True False  True]


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [28]:
m = np.random.random(10)
print(m)
print('\n')

m[m.argmax()] = 0
print("After replacing the max value with zero :" '\n', m)

[0.16568444 0.21257527 0.73175537 0.98128984 0.33160798 0.50736685
 0.86470527 0.69586313 0.24869755 0.2690899 ]


After replacing the max value with zero :
 [0.16568444 0.21257527 0.73175537 0.         0.33160798 0.50736685
 0.86470527 0.69586313 0.24869755 0.2690899 ]


# 9. How to print all the values of an array?

In [2]:
########################

np.set_printoptions(threshold=float('inf'))
arr3 = np.zeros((10,10))
print(arr3)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [60]:
arr4 = np.random.random((4,4))
print(arr4)
print('\n')
n = arr4.mean(axis=1, keepdims=True)
print("Mean value across all rows is :"'\n', n)
print("Shape of n is :", n.shape)
print('\n')
o = arr4 - n
print(o)

[[0.83732605 0.75122446 0.6990618  0.80455117]
 [0.59827311 0.70427134 0.23303144 0.26019126]
 [0.8667453  0.44343563 0.24290222 0.64854507]
 [0.54865341 0.93842419 0.3255163  0.56391652]]


Mean value across all rows is :
 [[0.77304087]
 [0.44894179]
 [0.55040706]
 [0.59412761]]
Shape of n is : (4, 1)


[[ 0.06428518 -0.02181641 -0.07397907  0.0315103 ]
 [ 0.14933132  0.25532955 -0.21591035 -0.18875052]
 [ 0.31633824 -0.10697143 -0.30750483  0.09813802]
 [-0.0454742   0.34429658 -0.2686113  -0.03021108]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [6]:
q = np.zeros(5)
print("Second Vector : ", q)
p = np.random.randint(0, len(q), 10)
print("Given Vector : ", p)
r= np.bincount(p, minlength=len(q))
print(r)
p = r+10
print("\n The addition of one gives :", p)

Second Vector :  [0. 0. 0. 0. 0.]
Given Vector :  [2 0 0 1 2 3 3 1 1 1]
[2 4 2 2 0]

 The addition of one gives : [3 5 3 3 1]


In [14]:
vect1 = np.arange(5)
print(vect1)
vect2 = np.random.randint(0, len(vect1), 5)
print(vect2)

np.add.at(vect2, vect1, 1)
print(vect2)

[0 1 2 3 4]
[1 2 4 4 1]
[2 3 5 5 2]


# 12.How to get the diagonal of a dot product?

In [21]:
#############

prod1 = np.random.random((4,4))
print(prod1)
prod2 = np.random.random((4,4))
print('\n', prod2)

final_prod = np.diag(np.dot(prod1,prod2))
print('\n The dot product is :', final_prod)

print('\n The alternate dot product method :', np.sum(prod1*prod2.T, axis=1))

[[0.21276204 0.96123325 0.48003772 0.38372425]
 [0.4445175  0.58219129 0.24674997 0.02370665]
 [0.80428803 0.1486999  0.00389288 0.75033339]
 [0.06611722 0.52510089 0.82678835 0.02849376]]

 [[0.53702303 0.50871074 0.20560252 0.63536012]
 [0.25726164 0.99250279 0.86554177 0.39055848]
 [0.34758625 0.36337677 0.57793848 0.25213566]
 [0.61637252 0.66593925 0.27189739 0.53430693]]

 The dot product is : [0.76491815 0.90940769 0.50033315 0.47077809]

 The alternate dot product method : [0.76491815 0.90940769 0.50033315 0.47077809]


# 13.How to find the most frequent value in an array?

In [20]:
arr5 = np.random.randint(1,20,15)
print(arr5)
v = np.bincount(arr5)
print("\n", v)
print("\n Most frequent value in array is :", np.argmax(v))

[ 6  5 12  8  9  8 10 10 13 14 15  8 14 15  1]

 [0 1 0 0 0 1 1 0 3 1 2 0 1 1 2 2]

 Most frequent value in array is : 8


# 14.How to get the n largest values of an array

In [32]:
################ amax

arr6 = np.arange(10)
print(arr6)
np.random.shuffle(arr6)
print(arr6)
n=3
w = arr6[np.argsort(arr6)[-n:]]
print("\n The largest value in the array is :", w)

[0 1 2 3 4 5 6 7 8 9]
[9 6 7 2 5 8 3 4 0 1]

 The largest value in the array is : [7 8 9]


# 15.How to create a record array from a regular array?

In [28]:
arr7 = np.array([1,2,3,4])
arr8 = np.array([5,6,7,8])
arr9 = np.array([11,22,33,44])
print(arr7)
print(arr8)
print(arr9)
r = np.core.records.fromarrays([arr7,arr8,arr9])
print("\n",r[0])
print(r[1])
print(r[2])

[1 2 3 4]
[5 6 7 8]
[11 22 33 44]

 (1, 5, 11)
(2, 6, 22)
(3, 7, 33)
